### PR TITLE
Effect.mergeAll should work when Z is an iterable, closes #1765

### LINKED ISSUE #1765: From Discord: `Effect.mergeAll` failing in case of `Z` being an array
### What version of Effect is running?

_No response_

### What steps can reproduce the bug?

The user described scenarios with `Effect.mergeAll` that yielded failures during runtime:

```ts
import { Effect, pipe,ReadonlyArray } from "effect";

const program = Effect.gen(function*($) {
    const result = yield* $(
        pipe([["a"],["aa"],["aaa"],["aaaa"]].map((a) => Effect.succeed(a)), Effect.mergeAll("", (b, a) => [...b,...a])))
      })

    Effect.runFork(program);
```

```
import { Effect, pipe,ReadonlyArray } from "effect";

const program = Effect.gen(function*($) {
    const result = yield* $(
        pipe([["a"],["aa"],["aaa"],["aaaa"]].map((a) => Effect.succeed(a)), Effect.mergeAll("", (b, a) => ReadonlyArray.appendAll(b,a))))
      })

    Effect.runFork(program);
```

Returns: [ 'a', 'aa', 'aaa', 'aaaa' ]
Yet Typewise, b should be a string.

```ts
import { Effect, pipe,ReadonlyArray } from "effect";

const program = Effect.gen(function*($) {
    const result = yield* $(
        pipe([["a"],["aa"],["aaa"],["aaaa"]].map((a) => Effect.succeed(a)), Effect.mergeAll([], (b, a) => [...b,...a])))
      })

    Effect.runFork(program);
```

```ts
import { Effect, pipe,ReadonlyArray } from "effect";

const program = Effect.gen(function*($) {
    const result = yield* $(
        pipe([["a"],["aa"],["aaa"],["aaaa"]].map((a) => Effect.succeed(a)), Effect.mergeAll(ReadonlyArray.empty<string>(), (b, a) => ReadonlyArray.appendAll(b,a))))
      })

    Effect.runFork(program);
```

Was described as being fine typewise, yet failing with `TypeError: ab is not a function` on runtime.

### What is the expected behavior?

The user would expect the possibility of the return type being an array.

### What do you see instead?

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by gcanti**

### CODE REVIEW

File: src/internal/fiberRuntime.ts [hunk 1]
```diff
@@ -2225,7 +2225,7 @@ export const mergeAll = dual<
     readonly batching?: boolean | "inherit" | undefined
   }) => Effect.Effect<R, E, Z>
 >(
-  (args) => Predicate.isIterable(args[0]),
+  (args) => Predicate.isFunction(args[2]),
```
Comment (tim-smart) [inline src/internal/fiberRuntime.ts:2228]: This will fail if Z is a function :) (even though that is a rare case)

Predicate.isIterable(args[0]) && Predicate.isFunction(args[2]) should cover all the cases.

Comment (gcanti) [reply src/internal/fiberRuntime.ts:2228]: I think that `args[2]` can only be:

- a function `f: (z: Z, a: A, i: number) => Z` (data-first) 
- an object or `undefined` (`options?: { ... }`) (data-last)

Comment (tim-smart) [reply src/internal/fiberRuntime.ts:2228]: Ah yes, nice 👍🏼

**Review by tim-smart — APPROVED** [review]
