### PR TITLE
Fix problematic prompt pasting

### LINKED ISSUE #1810: Copy-pasting in Prompt field only writes one character
When I paste some text in a prompt field, it only writes the first character

### PR DESCRIPTION
**Pull request by kitlangton**
## Type

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

All keypress events (including rapid-fire paste events) now get pushed into an eventsQueue immediately as they occur.

## Related

- Closes #1810

### CODE REVIEW

File: packages/platform-node-shared/src/internal/terminal.ts [hunk 1]
```diff
@@ -3,124 +3,98 @@ import * as Terminal from "@effect/platform/Terminal"
...
-      // The columns property can be undefined if stdout was redirected
-      columns: Effect.sync(() => output.columns || 0),
+      columns,
       readInput,
       readLine,
       display
     })
   })
 
-/** @internal */
```
Comment (tim-smart) [inline packages/platform-node-shared/src/internal/terminal.ts:122]: You can leave the internal comments here, so ts can strip away the internal types.

File: packages/platform-node-shared/src/internal/terminal.ts [hunk 2]
```diff
@@ -3,124 +3,98 @@ import * as Terminal from "@effect/platform/Terminal"
...
 import * as Layer from "effect/Layer"
 import * as Option from "effect/Option"
+import * as Queue from "effect/Queue"
 import * as readline from "node:readline"
 
-const defaultShouldQuit = (input: Terminal.UserInput): boolean =>
+const defaultShouldQuit = (input: Terminal.UserInput) =>
   input.key.ctrl && (input.key.name === "c" || input.key.name === "d")
 
-/** @internal */
```
Comment (tim-smart) [inline packages/platform-node-shared/src/internal/terminal.ts:11]: Another one.

File: packages/platform-node-shared/src/internal/terminal.ts (hunk 1 above)
Comment (kitlangton) [reply packages/platform-node-shared/src/internal/terminal.ts:122]: Doh! That was a mistake :) I'll fix

Comment (kitlangton) [reply packages/platform-node-shared/src/internal/terminal.ts:122]: Updated :)

File: packages/platform-node-shared/src/internal/terminal.ts (hunk 2 above)
Comment (kitlangton) [reply packages/platform-node-shared/src/internal/terminal.ts:11]: Updated :)
