### PR TITLE
Invalidate prepared-statement cache after loadExtension (Node)

### LINKED ISSUE #5457: statements prepared before loadExtension fail after
### What version of Effect is running?

3.17.11 @effect/sql-sqlite-node@0.45.1

### What steps can reproduce the bug?

```ts crsql_changes/scratchpad/try-crsql-repro.ts
import * as LibCrSql from "@effect-native/libcrsql/effect"
import * as Reactivity from "@effect/experimental/Reactivity"
import * as NodeRuntime from "@effect/platform-node/NodeRuntime"
import * as NodeSqlClient from "@effect/sql-sqlite-node"
import { Effect, Layer } from "effect"
import * as Console from "effect/Console"

const program = Effect.gen(function*() {
  const sql = yield* NodeSqlClient.SqliteClient.make({ filename: ":memory:" })
  const catchStuff = Effect.catchAll((error: { cause: unknown }) =>
    String(error.cause).includes("no such function")
      ? Effect.succeed([{ sha: null }])
      : Effect.fail(error)
  )
  yield* Console.log("BEFORE loadExtension", ...yield* sql`SELECT crsql_sha() as sha`.pipe(catchStuff))
  yield* sql.loadExtension(yield* LibCrSql.getCrSqliteExtensionPath())
  yield* Console.log("AFTER loadExtension", ...yield* sql`SELECT crsql_sha() as sha`.pipe(catchStuff))
  yield* Console.log("AFTER loadExtension", ...yield* sql`SELECT crsql_sha() as sha, 1`.pipe(catchStuff))
})

const mainLayer = Layer.mergeAll(
  Reactivity.layer
)

const main = program.pipe(Effect.provide(mainLayer), Effect.scoped)

NodeRuntime.runMain(main)
```

### What is the expected behavior?

Terminal output:
Restarting './try-crsql-repro.ts'
BEFORE loadExtension { sha: null }
AFTER loadExtension { sha: '0d62b52b4662ee1a762c9fd9264d48a91ab8df83' }
AFTER loadExtension { '1': 1, sha: '0d62b52b4662ee1a762c9fd9264d48a91ab8df83' }
Completed running './try-crsql-repro.ts'

### What do you see instead?

Terminal output:
Restarting './try-crsql-repro.ts'
BEFORE loadExtension { sha: null }
AFTER loadExtension { sha: null }
AFTER loadExtension { '1': 1, sha: '0d62b52b4662ee1a762c9fd9264d48a91ab8df83' }
Completed running './try-crsql-repro.ts'

### Additional information

running `prepareCache.invalidateAll` after `loadExtension` is probably the solution.
I'll send a PR with red test and a separate PR with the `prepareCache.invalidateAll` fix.

### PR DESCRIPTION
**Pull request by subtleGradient**
## Type

- [ ] Refactor
- [ ] Feature
- [x] Bug Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Invalidate the prepared-statement cache after `loadExtension`.

Prepared statements created before loading a SQLite extension could fail even
after the extension was loaded (e.g. "no such function" for extension
functions) because they were reused from the prepare cache. Clearing the cache
after `db.loadExtension` ensures statements are re-prepared with the updated
function set and query plan.

## Related

- Tests in PR #5458
- Closes #5457

### CODE REVIEW

File: packages/sql-sqlite-node/src/SqliteClient.ts [hunk 1]
```diff
@@ -202,10 +202,14 @@ export const make = (
...
-            try: () => db.loadExtension(path),
-            catch: (cause) => new SqlError({ cause, message: "Failed to load extension" })
-          })
+          return Effect.tap(
+            Effect.try({
+              try: () => db.loadExtension(path),
+              catch: (cause) => new SqlError({ cause, message: "Failed to load extension" })
+            }),
+            // Newly loaded extension may affect query planning, so clear the cache to ensure all queries are re-planned
+            () => prepareCache.invalidateAll
```
Comment (tim-smart) [inline packages/sql-sqlite-node/src/SqliteClient.ts]:
```suggestion
            }),
            () => prepareCache.invalidateAll
```

File: .changeset/clear-prepare-cache-on-load-extension.md [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+Prepared statements created before loading a SQLite extension could fail even
+after the extension was loaded (e.g. "no such function" for extension
+functions) because they were reused from the prepare cache. Clearing the cache
+after `db.loadExtension` ensures statements are re-prepared with the updated
+function set and query plan.
+
+Also adds tests that verify extension functions fail before load and succeed
+after, including the same SQL text succeeding post-load.
+
```
Comment (tim-smart) [inline .changeset/clear-prepare-cache-on-load-extension.md]:
```suggestion
Invalidate the prepared-statement cache after `loadExtension`.
```
